name: Deploy PubSub + Kafka + RabbiMQ with Terraform and Ansible
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, prod)"
        required: true
        default: dev

permissions:
  contents: read
  id-token: write

jobs:
  security-github-actions:
    name: Security SSH Key
    runs-on: ubuntu-latest
    outputs:
      ssh_public_key: ${{ steps.generate_ssh_key.outputs.ssh_public_key }}
      ssh_private_key_b64: ${{ steps.generate_ssh_key.outputs.ssh_private_key_b64 }}
    steps:
      - name: Generar clave SSH temporal
        id: generate_ssh_key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N "" -C "gha@runner"

          # Exportar clave pública
          echo "ssh_public_key=$(cat ~/.ssh/id_rsa.pub)" >> $GITHUB_OUTPUT

          # Exportar clave privada codificada en base64
          PRIVATE_KEY_B64=$(base64 -w 0 ~/.ssh/id_rsa)
          echo "ssh_private_key_b64=$PRIVATE_KEY_B64" >> $GITHUB_OUTPUT

      - name: Verificar variable ssh_public_key
        run: |
          echo "${{ steps.generate_ssh_key.outputs.ssh_public_key }}"

      - name: Verificar variable ssh_private_key
        run: |
          echo "${{ steps.generate_ssh_key.outputs.ssh_private_key }}"